language: python
dist: xenial
cache: pip

python:
  - "3.7"

install:
  - wget https://github.com/hakimel/reveal.js/archive/master.zip
  - unzip master.zip
  - mv reveal.js-master reveal.js

script:
  - python exhibit.py

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
  git checkout --orphan gh-pages
  git rm -rf --cached .
  git add -f --ignore-errors index.html gallery reveal.js
  git -c user.name='travis' -c user.email='travis' commit -m init
  git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
  fi
